function p=line_parent_child(xyz_tb,parent,child)
p=plot3([xyz_tb(child,1),xyz_tb(parent,1)], ...
    [xyz_tb(child,2),xyz_tb(parent,2)], ...
    [xyz_tb(child,3),xyz_tb(parent,3)],"-",LineWidth=1.5);
end