function  PlotRULine(gca,axes_xcolor,axes_ycolor,lwidth)
%UNTITLED4 此处显示有关此函数的摘要
%   此处显示详细说明

ax2 = axes('Position', get(gca, 'Position'),...
    'XAxisLocation', 'top',...
    'YAxisLocation', 'right',...
    'Color', 'none',...
    'XColor', axes_xcolor,...
    'YColor', axes_ycolor,...
    'LineWidth',lwidth);
set(ax2, 'YTick', []);
set(ax2, 'XTick', []);

end