
function SetAxesLog(gca,xlimit,ylimit,xtrue,ytrue)
if xtrue==1 &&ytrue==1
    set(gca          , ...
        'XLim'          , [min(xlimit(1), [], 'omitnan') max(xlimit(2), [], 'omitnan')], ...
        'XScale'        , 'log', ...
        'XColor'        , 'k', ...
        'YLim'          , [min(ylimit(1), [], 'omitnan') max(ylimit(2), [], 'omitnan')], ...
        'YScale'        , 'log', ...
        'Box'           , 'off');
elseif xtrue==1
    set(gca          , ...
        'XLim'          , [min(xlimit(1), [], 'omitnan') max(xlimit(2), [], 'omitnan')], ...
        'XScale'        , 'log', ...
        'XColor'        , 'k', ...
        'Box'           , 'off');
elseif ytrue==1
    set(gca          , ...
        'YLim'          , [min(ylimit(1), [], 'omitnan') max(ylimit(2), [], 'omitnan')], ...
        'YScale'        , 'log', ...
        'Box'           , 'off');
end
set(gca, 'TickDir', 'out','LineWidth', 1.5,'Layer','top','YColor','k','XColor','k');
end